spring:
  datasource:
    url: jdbc:mysql://localhost:3306/presse
    username: root
    password: root
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
    hibernate: # validate | update | create | create-drop
      ddl-auto: create-drop
